[theme]
background = "black"
primary = "white"
secondary = "light black"
title = "yellow"
playing = "yellow"
playing_selected = "yellow"
playing_bg = "black"
highlight = "yellow"
highlight_bg = "black"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "yellow"
statusbar_bg = "yellow"
cmdline = "light white"
cmdline_bg = "black"

[keybindings]
"space" = "playpause"

[global]
use_nerdfont = true
volnorm = true
volnorm_pregain = -6
